### ISSUE TITLE
Checking C compiler fails on apple arm64

### ISSUE THREAD

**Issue by workbear** [s-u/uuid#11]
It is not possible to install the uuid package in R4.0... on Apple M1.
The compiler check fails. Other R packages compile fine from source. This seems specific to UUID.
Can you please have a look?
Thanks

uuid_0.1-4.tar.gz downloaded 48 KB

installing *source* package ‘uuid’ ...
package ‘uuid’ successfully unpacked and MD5 sums checked
using staged installation
checking for gcc... clang
checking whether the C compiler works... no
configure: error: in `/private/var/folders/xl/kpqy_tnj25dcs7qmkz75h7300000gn/T/RtmpYkXGeS/R.INSTALL2f0f2eeb8901/uuid':
configure: error: C compiler cannot create executables
See `config.log' for more details
ERROR: configuration failed for package ‘uuid’
removing ‘/opt/homebrew/lib/R/4.0/site-library/uuid’
`

**Comment by s-u** [comment]
Not enough details, likely system broken by homebrew (mixing native code with homebrew). Check `config.log` for details.
