### ISSUE TITLE
Compiling with icc on linux

### ISSUE THREAD

**Issue by BertrandServin** [s-u/uuid#3]
Hi,

I am trying to install the uuid package on a Debian testing, with R compiled with icc. I get the following errors:

`
icc -std=c99 -I/opt/lib/R/include -DNDEBUG -I/usr/local/include -I/usr/local/include    -fpic  -g -O3 -wd188 -ip -xHost  -c gen_uuid.c -o gen_uuid.o
gen_uuid.c(140): error: incomplete type is not allowed
    struct ifreq    ifr, *ifrp;
                    ^

gen_uuid.c(141): error: incomplete type is not allowed
    struct ifconf   ifc;
                    ^

gen_uuid.c(175): error: incomplete type is not allowed
    for (i = 0; i < n; i+= ifreq_size(*ifrp) ) {
                           ^

gen_uuid.c(177): error: pointer to incomplete class type is not allowed
        strncpy(ifr.ifr_name, ifrp->ifr_name, IFNAMSIZ);
                              ^

gen_uuid.c(177): error: identifier "IFNAMSIZ" is undefined
        strncpy(ifr.ifr_name, ifrp->ifr_name, IFNAMSIZ);
                                              ^

gen_uuid.c(291): warning #266: function "syscall" declared implicitly
    ul_jrand_seed[2] = ul_jrand_seed[2] ^ syscall(__NR_gettid);
                                          ^

gen_uuid.c(293): warning #266: function "jrand48" declared implicitly
        *cp++ ^= (jrand48(tmp_seed) >> 7) & 0xFF;
                  ^

gen_uuid.c(351): warning #266: function "fdopen" declared implicitly
            state_f = fdopen(state_fd, "r+");
                      ^

gen_uuid.c(432): warning #266: function "ftruncate" declared implicitly
        if (ftruncate(state_fd, len) < 0) {
            ^

compilation aborted for gen_uuid.c (code 2)
`

Any clues on how to solve this ?
thanks for your work and help :)

**Comment by GearFear** [comment]
Same bug - due to it cannot install IRkernel :( Shame on you uiid

**Comment by JavierCVilla** [comment]
Any news about this problem?

**Comment by jeffreyhanson** [comment]
Any updates?

**Comment by Erog38** [comment]
Still need this fix as well. It's a shame to not see any response from the developer on this. We were able to get it compiled by removing the -std=c99 flag and letting it default.

**Comment by s-u** [comment]
As the errors suggest, the system or compiler is missing definitions in headers. Since `icc` is commercial there is nothing we can do, ask Intel for support.
