### ISSUE TITLE
support "v1mc" (random MAC)

### ISSUE THREAD

**Issue by r2evans** [s-u/uuid#5]
Some discussions insinuate that using a version 1 UUID (using the MAC address encoded in the last 6 bytes) can be a concern, tracing back to the source computer. One suggested alternative is to randomize the last 6 bytes, keeping the same time/sequence in the first 10 bytes.

Do you think this feature is important enough to implement in C?

If so, I offer that the quality of randomness required for good version 4 UUIDs (completely random) is not "as required" for the MAC address. That is, even if it is determined that the host does not have a *"sufficiently reliable source of random numbers"*, it would still be useful to use randomizeable MAC address with time/sequenced UUIDs.

**Comment by s-u** [comment]
I suspect this is moot - `libuuid` uses good random source when available.
